name: Build

on:
  release:
    types:
      - published

jobs:
  docker:
    name: Docker
    runs-on: ubuntu-latest
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: delegatorau
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v2.6.1
        with:
          push: true
          tags: delegatorau/prometheus-ecs-sd:${{ env.GITHUB_REF }}
